name: Atualizador de Dados

on:
  schedule:
    - cron: '0 12,16,20,23,02 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 🔥 Isso reforça a permissão de escrita direto no código:
    permissions:
      contents: write
      
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 # Versão v4 (mais nova)

      - name: Configurar Python
        uses: actions/setup-python@v5 # Versão v5 (mais nova)
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: pip install requests

      - name: Executar Robô
        run: python robo.py

      - name: Salvar Mudanças
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add transacoes.json
          # O comando abaixo evita erro se não houver notas novas
          git commit -m "Dados atualizados automaticamente" || echo "Sem mudanças para salvar"
          git push
